### ISSUE TITLE
A small issue with chapter 2 code running it on kaggle 

### ISSUE THREAD

**Issue by abdelkareemkobo** [Mohamed-Ahmed-Abo-El-Enen/LargeLanguageModels#1]
Hello, Mohammed. I am so amazed with your work and implementations, which motivated me to start reading the book. I finished the first two chapters and tried applying the tasks on Arabic language with Arabian models

[A small error is in the installing datasets. ](https://discuss.huggingface.co/t/solved-module-numpy-has-no-attribute-object-np-object-was-a-deprecated-alias-for-the-builtin-object-for-train-dataset-map-tokenize-batched-true-in-notebook/69669)

**Comment by Mohamed-Ahmed-Abo-El-Enen** [comment]
Hello Adel

Yes this error appear to me each time I work on kaggle not colab, the code
work fine on colab because it's install the latest datasets version but
kaggle need 2.15 an old version to be compatible with the rest on env
packages, you can just change the install dataset on kaggle to old one or
work directly on colab it will fit on it's memory

Best Regards
Mohamed Ahmed

**Comment by Mohamed-Ahmed-Abo-El-Enen** [comment]
So sorry about name mistake was talking to work partner names Adel

**Comment by Mohamed-Ahmed-Abo-El-Enen** [comment]
Yes this error appear to me each time I work on kaggle not colab, the code
work fine on colab because it's install the latest datasets version but
kaggle need 2.15 an old version to be compatible with the rest on env
packages, you can just change the install dataset on kaggle to old one or
work directly on colab it will fit on it's memory

**Comment by abdelkareemkobo** [comment]
Thanks, for the clarification.
